-- 001_create_core_tables.sql
-- Canonical schema for FreshersJob.
-- Safe to run multiple times.

begin;

create table if not exists public.jobs (
  id bigint generated by default as identity primary key,
  title text not null,
  company_name text,
  company text,
  state text,
  city text,
  location text,
  job_type text,
  experience_level text,
  salary_min numeric(12,2),
  salary_max numeric(12,2),
  description text,
  requirements text,
  skills text[] not null default '{}',
  status text not null default 'active',
  employer_id text,
  created_by text,
  applications_count integer not null default 0,
  company_logo text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public."UserProfile" (
  id bigint generated by default as identity primary key,
  created_by text not null,
  role text not null,
  full_name text,
  headline text,
  bio text,
  location text,
  phone text,
  skills text[] not null default '{}',
  education text,
  experience_years integer,
  resume_url text,
  profile_photo text,
  company_name text,
  company_logo text,
  company_website text,
  company_size text,
  linkedin_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  job_id bigint not null,
  candidate_id text,
  candidate_email text,
  candidate_name text,
  candidate_phone text,
  candidate_headline text,
  candidate_skills text[] not null default '{}',
  employer_id text,
  job_title text,
  company_name text,
  cover_letter text,
  resume_url text,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.saved_jobs (
  id bigint generated by default as identity primary key,
  job_id bigint not null,
  user_id text,
  user_email text,
  created_at timestamptz not null default now()
);

commit;
