import React from 'react';

// Simple placeholder component shown when the user hasn't finished
// registering. The original project generated by Base44 would normally
// include a more complete implementation but for the purposes of running the
// app we just render a minimal message.

export default function UserNotRegisteredError() {
  return (
    <div className="p-4 text-center text-red-600">
      <p>User not registered. Please complete your profile.</p>
    </div>
  );
}
